# Базовый образ с которого мы начнём создание своего собственного образа
FROM nginx:1.16.0

ENV WORKDIR /usr/share/nginx/html

WORKDIR ${WORKDIR}
# То же что и 
# WORKDIR /usr/share/nginx/html

LABEL path ${WORKDIR}

# ADD
# COPY
# ENV
# EXPOSE
# FROM
# LABEL
# STOPSIGNAL
# USER
# VOLUME
# WORKDIR

COPY index.html index.html